[window]
opacity = 1.0

padding = { x = 4, y = 4 }

[scrolling]
history = 2000

[font]
size = 10.0

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic" 

[bell]
duration = 0 

[cursor]
style = { shape = "Block", blinking = "Off" }

[colors]

[colors.primary]
background = "#f6fbf4"
foreground = "#171d19"

[colors.cursor]
text   = "#f6fbf4"
cursor = "#266a4a"

[colors.selection]
text       = "#ffffff"
background = "#266a4a"

[colors.normal]
black   = "#dce5dc"
red     = "#ba1a1a"
green   = "#266a4a"
yellow  = "#3c6472"
blue    = "#4e6356"
magenta = "#acf2c9"
cyan    = "#d0e8d7"
white   = "#171d19"

[colors.bright]
black   = "#d0e8d7"
red     = "#ffdad6"
green   = "#acf2c9"
yellow  = "#c0e9f9"
blue    = "#d0e8d7"
magenta = "#266a4a"
cyan    = "#4e6356"
white   = "#404943"