# Player: mpv, vlc
player="mpv"

# Resolution: best, 2160, 1440, 1080, 720, 480, 360, 240, 144
resolution="720"

# Codec: h264, av1, vp9
codec="h264"

# Playlist Mode: true/false
playlist="true"

# Max Playlist Items (number)
playlist_limit="50"

# Cache Management (in MB)
cache_max_mb="40"
cache_min_mb="35"