# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#171d19"

# Title color for boxes
theme[title]="#266a4a"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#4e6356"

# Background color of selected item in processes box
theme[selected_bg]="#266a4a"

# Foreground color of selected item in processes box
theme[selected_fg]="#ffffff"

# Color of inactive/disabled text
theme[inactive_fg]="#404943"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#3c6472"

# Cpu box outline color
theme[cpu_box]="#707972"

# Memory/disks box outline color
theme[mem_box]="#707972"

# Net up/down box outline color
theme[net_box]="#707972"

# Processes box outline color
theme[proc_box]="#707972"

# Box divider line and small boxes line color
theme[div_line]="#c0c9c1"

# Temperature graph colors
theme[temp_start]="#4e6356"
theme[temp_mid]="#266a4a"
theme[temp_end]="#ba1a1a"

# CPU graph colors
theme[cpu_start]="#4e6356"
theme[cpu_mid]="#266a4a"
theme[cpu_end]="#ba1a1a"

# Mem/Disk free meter
theme[free_start]="#4e6356"
theme[free_mid]=""
theme[free_end]="#d0e8d7"

# Mem/Disk cached meter
theme[cached_start]="#3c6472"
theme[cached_mid]=""
theme[cached_end]="#c0e9f9"

# Mem/Disk available meter
theme[available_start]="#266a4a"
theme[available_mid]=""
theme[available_end]="#acf2c9"

# Mem/Disk used meter
theme[used_start]="#ba1a1a"
theme[used_mid]=""
theme[used_end]="#ffdad6"

# Download graph colors
theme[download_start]="#4e6356"
theme[download_mid]="#266a4a"
theme[download_end]="#3c6472"

# Upload graph colors
theme[upload_start]="#4e6356"
theme[upload_mid]="#266a4a"
theme[upload_end]="#3c6472"