input-ipc-server=/tmp/modern_labwc_mpv.sock
osc=no
osd-bar=no    
border=yes
#window-dragging=yes                   
keepaspect=yes
keepaspect-window=no                
#keep-open=yes                  
force-window=yes              
cursor-autohide=1000            
autofit=70%x70%                 
hwdec=auto-safe
