[General]
Name=Everforest Light
Description=A Qt/KDE theme based on the Everforest Light GTK style.

[ColorScheme]
active_colors=#4a4a4a, #e9ede6, #ffffff, #f7f9f6, #f4f6f3, #eff2ee, #4a4a4a, #000000, #4a4a4a, #f4f6f3, #f4f6f3, #ffffff, #bcccdc, #f4f6f3, #3a6b57, #325e4c, #e9ede6, #ffffff, #f4f6f3, #4a4a4a, #9c9c9c

inactive_colors=#9c9c9c, #e6eae4, #fafcf9, #f4f6f3, #f2f4f1, #eceedb, #9c9c9c, #333333, #9c9c9c, #f2f4f1, #f2f4f1, #ffffff, #e6eae4, #333333, #376552, #2f5647, #e6eae4, #ffffff, #f2f4f1, #9c9c9c, #afafaf

disabled_colors=#a1a1a1, #f4f6f3, #e9ede6, #eff2ee, #f1f3f0, #f2f4f1, #a1a1a1, #6e6e6e, #a1a1a1, #f4f6f3, #f4f6f3, #ffffff, #f4f6f3, #8a8a8a, #859f95, #758b80, #f4f6f3, #ffffff, #f4f6f3, #a1a1a1, #c2c2c2