[General]
Name=Lavender Pastel
Description=A Qt/KDE theme based on the Lavender Pastel GTK style.

[ColorScheme]
active_colors=#4c4c6d, #e8e8ed, #ffffff, #f5f5f7, #f5f5f7, #ebebed, #4c4c6d, #000000, #4c4c6d, #f5f5f7, #f5f5f7, #ffffff, #b7a9de, #ffffff, #9575cd, #7f62b0, #e8e8ed, #ffffff, #f5f5f7, #4c4c6d, #a2a2b7

inactive_colors=#a1a1b5, #e5e5ea, #fafafc, #f2f2f5, #f3f3f5, #e8e8ec, #a1a1b5, #333333, #a1a1b5, #f3f3f5, #f3f3f5, #ffffff, #e5e5ea, #333333, #9e82d1, #876ab3, #e5e5ea, #ffffff, #f3f3f5, #a1a1b5, #b4b4c5

disabled_colors=#a2a2b7, #f5f5f7, #e8e8ed, #ebebed, #f2f2f5, #f3f3f5, #a2a2b7, #6e6e6e, #a2a2b7, #f5f5f7, #f5f5f7, #ffffff, #f5f5f7, #8a8a8a, #b29ed9, #9985ba, #f5f5f7, #ffffff, #f5f5f7, #a2a2b7, #c2c2cf