# Core Colors
background            #f6fbf4
foreground            #171d19
selection_foreground  #ffffff
selection_background  #266a4a
cursor                #266a4a
cursor_text_color     #f6fbf4

# Regular Colors
color0  #dce5dc
color1  #ba1a1a
color2  #266a4a
color3  #3c6472
color4  #4e6356
color5  #acf2c9
color6  #d0e8d7
color7  #171d19

# Bright Colors
color8  #f6fbf4
color9  #ffdad6
color10 #acf2c9
color11 #c0e9f9
color12 #d0e8d7
color13 #266a4a 
color14 #4e6356
color15 #404943