[colors-dark]
alpha=1

background=f6fbf4
foreground=171d19

# Better cursor contrast
cursor=f6fbf4 266a4a

selection-foreground=ffffff
selection-background=266a4a

# REGULAR COLORS 
regular0=dce5dc          # black
regular1=ba1a1a                    # red
regular2=266a4a                  # green
regular3=3c6472                 # yellow
regular4=4e6356                # blue
regular5=acf2c9        # magenta
regular6=d0e8d7      # cyan
regular7=171d19               # white

# BRIGHT COLORS 
bright0=f6fbf4
bright1=ffdad6
bright2=acf2c9
bright3=c0e9f9
bright4=d0e8d7
bright5=266a4a
bright6=4e6356
bright7=404943